a = input('Enter the first number: ')
b = input('Enter the second number: ')
a = int(a)
b = int(b)
c = a + b
print(f'{a} + {b} = {c}')
c = a - b
print(f'{a} - {b} = {c}')
c = a / b
print(f'{a} / {b} = {c}')
c = a * b
print(f'{a} * {b} = {c}')
c = a % b
print(f'{a} % {b} = {c}')
c = a ** b
print(f'{a} ** {b} = {c}')
c = a // b
print(f'{a} // {b} = {c}')